In [33]:
#importing Numpy Library
import numpy as np

# 1st Program to Create an array and print its elements

In [34]:
array=np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [35]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 2nd Program: Create array and print its Shape

In [36]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(array.shape)

(2, 4)


# 3rd Program to print reverse elements of array

In [37]:
array= np.array([1, 2, 3, 4, 5, 6, 7])

print(array[::-1])

[7 6 5 4 3 2 1]


# 4th Program to Create an array and resize it

In [38]:
array=np.arange(0,50,2).reshape(5,5)
print(array)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


# 5th program to Sort array in ascending order 

In [24]:
array = np.array([12, 51, 6, 9, 1, 15, 23, 4, 7])

print(np.sort(array)) 

[ 1  4  6  7  9 12 15 23 51]


# 6th program to demostrate CSR Marix

In [1]:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]]))


# 7th Write a Program to Find the shortest path between all pairs of elements

In [4]:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]]))


# 8th Write a Program to Traverse the graph breadth first for given adjacency matrix

In [3]:
import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(breadth_first_order(newarr, 1)) 

(array([1, 0, 2, 3]), array([    1, -9999,     1,     1]))
